os:windows
env:
  global:
   #   The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "CJQZtLgj9Z5yhmgY3h1NoIa+dMlbwEIPKRTA2XQfQeIE8o4rGNQVv6vWBFw1GAfYBF37FshZKAf2lzUc3odt1GWm5JQGVySYr3fPP6XGrAP4xwDL825QAUU2BXN8G/woSVL9WqBehyS/PelVvK9TleUP+iOYnQSxpMblq1m1p1OAiRBOLDYenCyqT/YCe1AVQDzN6Ls1VorJHb6C80slSKqeNKTcUYv4TTGNdb55fLwk3wxD70c1S4cSXPS7AxM1IUk+Tcsf7VzLeJ4QS0auuAGXLjNzF+3wxHKeEj4sc0pemFHbcD5xz0Dua4vIinnU6E/IlXDnd/L6UqiVO4tvtxi24hMPLvuUlRtIiIP1jbMhOeUybDtIXJa1ZbSz7YWDBKiOQOpRErLKnh840izqEf8nDZX8jlgciqz/FrZQ9EoUzJ6PqY0gLV46F5i5gvvsOYWzcPbHbubsUm4esDK36a63ett2u9M+xCPmEKEGIx8yt1xAfvaUt2t4onYZG4di+68/JLgoRI3rpNTAqHfPjHLrq8uf70YlbF1ny7rLibs7+wXClLaiLCdXuOgTQYgBJhv+umR9Zpv764VOA2PY44pr1uyuQJOTQr4uoyT0FhfZFmqvJ9rz/l3DyS1XcUMB8tCPP4MqR52psE6AAuBN5/B6PB6SZ1idStH5by3ioloM="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - choco install mingw

script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then mingw32-make --eval="COMPILER := MINGW" ; fi

addons:
  coverity_scan:
    project:
      name: "LADSoft/OrangeC"
      description: "Orange C compiler"
    notification_email: touchstone222@runbox.com
    build_command_prepend: 
	- move ladsoft\orangec .
        - path=\mingw\bin;\orangec\bin;%PATH%
        - set ORANGEC=\orangec
        - cd orangec\src
    build_command: mingw32-make --eval="COMPILER := MINGW"
    branch_pattern: coverity_scan