os: windows
language: c
compiler:
 - clang

env:
  global:
   #   The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "hT16bO0CRUWw/9aN2J9cOX90O8K/psKe8T8mp5cIq39ImK1D5PpAzyGylNaODPKo4YOl4yHBU90M9Q4nVIb+n7eSD4wH3OqpvFXbHaJNuD6N7/DcyC1sm+j+ZnwYcpC1j0ahvuts6L6iDKwtSCB95NsqnJGJhWY70/5PUTMI4LT3MKCP7s3uMzvBSC9HVuwr4+wKY4fYGIkfxzS2pwphTZvhA0hXQunXncE5z/D71pP2/BvAJtyEjTIZikWZqPHobSbBIJnR68DBdWZtWZ3u5IpiI3a8rc35TwVkaA9L9COFIRPioUlmG7FINtXZtjs5WZCrBgW+ofud+dwm7WQENSiGPlPMs8hAwC/y5cwvfMlk4sPIkqBppGQ/3XNZFuJNiQYnmxvl6/5j++Hrpa8UQgd4vZdmXs5T/fyi4+P9Q2NojKnqwCnrX4izX4vrFNFyiVERXsb+lD1kmwBPHC4UwTklAFaxtDI1e6n7iw5LmF2ylAIfC4e3JqKE4qgfOpPGPXJQGFlT7+KLNE+pgqptbva8zeS8DZI503Nj2vsIG7bsa3LcZWiNe1p+OlJbxsR4K8IYmtoBiiKPxWNRwXShv3arSFI5S1S/Nt9U+XnGI1K1tC8u3JY8vhZhceSlqgkndy9O+9K2hUKK01G4qSBlPgMVnMvFqXRkbvD+HPTPcMU="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - choco install mingw

script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then mingw32-make --eval="COMPILER := MINGW" ; fi

addons:
  coverity_scan:
    project:
      name: "LADSoft/OrangeC"
      description: "Orange C compiler"
    notification_email: touchstone222@runbox.com
    build_command_prepend: ./travis-configure
    build_command: omake --eval="COMPILER := CLANG"
    branch_pattern: coverity_scan