image: Visual Studio 2017

install:
    - choco install InnoSetup
    - set PATH=c:\orangec\bin;%PATH%;C:\Program Files (x86)\Inno Setup 5
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
    - set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
    - set ORIGPATH=%PATH%
    - set ORANGEC=c:\ORANGEC

environment:
  matrix:
    - BUILD_PROFILE: MS
    - BUILD_PROFILE: MINGW64
 
 
build_script:
        
        - cd ..\..
        - move projects\orangec .
        - mkdir \orangec\temp
        - cd orangec\src
        - copy omake.exe \orangec\temp
#        - c:\orangec\temp\omake -DCOMPILER=MS -B fullbuild 
        - mingw32-make fullbuild --eval="COMPILER=$(BUILD_PROFILE)"
        - c:\orangec\bin\occ /V
        - copy omake\omake.exe \orangec\temp
        - c:\orangec\temp\omake -DNOMAKEDIR -DCOMPILER=OCC -B fullbuild 
        - c:\orangec\bin\occ /V
        - copy omake\omake.exe \orangec\temp
        - c:\orangec\temp\omake -DNOMAKEDIR -DCOMPILER=OCC -B fullbuild 
        - c:\orangec\bin\occ /V
        - copy omake\omake.exe \orangec\temp
        - c:\orangec\temp\omake -DNOMAKEDIR -DCOMPILER=OCC -B fullbuild 
        - path=%ORIGPATH%
        - cd ..\tests
        - omake -B
        - cd ..\.. 
        - move orangec projects

artifacts:
  - path: "bin\\ocpp.exe"
    name: ocpp
  - path: "bin\\ocide.exe"
    name: ocide
  - path: "bin\\occpr.exe"
    name: occpr
  - path: "bin\\occ.exe"
    name: occ
  - path: "bin\\coff2ieee.exe"
    name: coff2ieee
  - path: "bin\\omake.exe"
    name: omake
  - path: "bin\\oimplib.exe"
    name: oimplib
  - path: "bin\\obrc.exe"
    name: obrc
  - path: "bin\\ogrep.exe"
    name: ogrep
  - path: "bin\\dlpm.exe"
    name: dlpm
  - path: "bin\\dlpe.exe"
    name: dlpe
  - path: "bin\\dlmz.exe"
    name: dlmz
  - path: "bin\\dlle.exe"
    name: dlle
  - path: "bin\\dlhex.exe"
    name: dlhex
  - path: "bin\\olib.exe"
    name: olib
  - path: "bin\\olink.exe"
    name: olink
  - path: "bin\\oasm.exe"
    name: oasm
  - path: "bin\\ocl.exe"
    name: ocl
  - path: "dist\\*.*"
    name: releasefiles